seed_everything: true
per_run_seed: true
tags:
  exp: &exp pixeldit_c2i_bs256
torch_hub_dir: null
huggingface_cache_dir: null
auto_resume: true
trainer:
  default_root_dir: ./train_logs/
  accelerator: gpu
  strategy: ddp
  devices: 8
  num_nodes: 1
  precision: bf16-mixed
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  logger:
      class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: pix_dit_c2i
        name: *exp
  num_sanity_val_steps: 0
  max_steps: 1600000
  val_check_interval: 100000
  check_val_every_n_epoch: null
  log_every_n_steps: 50
  deterministic: null
  inference_mode: true
  use_distributed_sampler: false
  callbacks:
    - class_path: src.utils.CheckpointHook
      init_args:
        every_n_train_steps: 10000
        save_top_k: -1
        save_last: true
    - class_path: src.utils.SaveImagesHook
      init_args:
         save_dir: val_256_xl
         save_compressed: true
model:
  enable_profiling: true
  profiling_print_freq: 1000
  profiling_warmup_steps: 100
  override_lr_on_resume: null
  override_ema_decay_on_resume: null
  num_classes: 1000
  denoiser:
    class_path: pixdit_core.pixeldit_c2i.PixDiT
    init_args:
        in_channels: 3
        patch_size: 16
        num_groups: 16
        hidden_size: &hidden_dim 1152
        patch_depth: 26
        pixel_depth: 4
        num_classes: 1000
        pixel_hidden_size: 16
  diffusion_trainer:
    class_path: src.diffusion.REPATrainer
    init_args:
      lognorm_t: true
      timeshift: 1.0
      encoder:
        class_path: src.diffusion.DINOv2
      align_layer: 8
      proj_denoiser_dim: *hidden_dim
      proj_hidden_dim: *hidden_dim
      proj_encoder_dim: 768
      egfm_sigma0: 3.5
      egfm_curve: smootherstep
      egfm_release_start: 0.0
      egfm_release_end: 1.0
      scheduler: &scheduler src.diffusion.LinearScheduler
  diffusion_sampler:
    class_path: src.diffusion.FlowDPMSolverSampler
    init_args:
      num_steps: 100
      guidance: 3.25
      timeshift: 1.0
      guidance_interval_min: 0.1
      guidance_interval_max: 1.0
      scheduler: *scheduler
      w_scheduler: src.diffusion.LinearScheduler
      guidance_fn: src.diffusion.simple_guidance_fn
      step_fn: src.diffusion.ode_step_fn
  ema_tracker:
    class_path: src.utils.SimpleEMA
    init_args:
      decay: 0.9999
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 1e-4
      weight_decay: 0.0
data:
  train_dataset:
    class_path: src.data.CustomINH5Dataset
    init_args:
      data_dir: ./imagenet256_data
  eval_dataset:
    class_path: src.data.ClassLabelRandomNDataset
    init_args:
      num_classes: 1000
      max_num_instances: 50000
      latent_shape:
        - 3
        - 256
        - 256
  pred_dataset:
    class_path: src.data.ClassLabelRandomNDataset
    init_args:
      num_classes: 1000
      max_num_instances: 50000
      latent_shape:
        - 3
        - 256
        - 256
  train_batch_size: 32
  train_num_workers: 4
  pred_batch_size: 32
  pred_num_workers: 1
